#!/usr/bin/env bash
# fizz buzz fizzbuzz


for ((n = 1 ; n <= 100 ; ++n))
do
	if [ $((n % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((n % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((n % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$n"
	fi
done
