#!/usr/bin/env bash
# displays 'bad luck' for n -eq 4, 'good luck' for n -eq 8. decimal

count=1
bad="bad luck"
good="good luck"
praise="Best School"
while [ $count -le  10 ] 
do
	if [ $count -eq 4 ]
	then
		echo "$bad"
	elif [ $count -eq 8 ]
	then
		echo "$good"
	else
		echo "$praise"
	fi
	((++count))
done
