#!/usr/bin/env bash
# gives info about a file

filename="school"
if [ -e "$filename" ]
then
	echo "$filename file exists"
else
	echo "$filename file does not exist"
fi

if [ -s "$filename" ]
then
	echo "$filename is not empty"
else
	echo "$filename is empty"
fi

if [ -f "$filename" ]
then
	echo "$filename is a regular file"
fi
