#!/usr/bin/env bash
# gives info about a file

filename="school"
if [ -e "$filename" ]
then
	echo "$filename file exists"
	# -f for file presumably. is file a (regular) file?
	if [ -f "$filename" ]
	then
		echo "$filename is a regular file"
	fi

	# is the file empty?
	if [ -s "$filename" ]
	then
		echo "$filename is not empty"
	else
		echo "$filename is empty"
	fi

else
	echo "$filename file does not exist"
fi
